apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  source: 
    chart: clickhouse
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 3.6.8
    # https://github.com/bitnami/charts/tree/main/bitnami/clickhouse
    # helm:
    #   values: |

  destination:
    server: "https://kubernetes.default.svc"
    namespace: clickhouse
