apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  source:
    chart: postgresql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 12.8.3
    # https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    helm:
      values: |
        fullnameOverride: postgres
        auth:
          postgresPassword: password
          database: postgres
          username: postgres
          password: password

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kafka
