apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-ui
  namespace: debezium
  labels:
    application: debezium-ui
    role: debezium-ui

spec:
  replicas: 1
  selector:
    matchLabels:
      application: debezium-ui
      role: debezium-ui
  template:
    metadata:
      labels:
        application: debezium-ui
        role: debezium-ui
    spec:
      # Note: needed to create connector from UI
      # serviceAccountName: postgres-client
      containers:
        - name: debezium-ui
          image: debezium/debezium-ui:2.2
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CONNECT_URIS
              value: http://debezium:8083

          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "100m"
