apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-01"
spec:
  configuration:
    clusters:
      - name: "simple"
    


  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              livenessProbe:
                failureThreshold: 10
                exec:
                  command:
                  - wget -qO- localhost:8123/ping
                initialDelaySeconds: 60
                periodSeconds: 3
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                exec:
                  command:
                  - wget -qO- localhost:8123/ping
                initialDelaySeconds: 10
                periodSeconds: 3
                successThreshold: 1
                timeoutSeconds: 1

# spec:
#   containers:
#     - image: 'clickhouse/clickhouse-server:latest'
#       imagePullPolicy: Always
#       livenessProbe:
#         failureThreshold: 10
#         httpGet:
#           path: /ping
#           port: http
#           scheme: HTTP
#         initialDelaySeconds: 60
#         periodSeconds: 3
#         successThreshold: 1
#         timeoutSeconds: 1
#       name: clickhouse
#       ports:
#         - containerPort: 9000
#           name: tcp
#           protocol: TCP
#         - containerPort: 8123
#           name: http
#           protocol: TCP
#         - containerPort: 9009
#           name: interserver
#           protocol: TCP
#       readinessProbe:
#         failureThreshold: 3
#         httpGet:
#           path: /ping
#           port: http
#           scheme: HTTP
#         initialDelaySeconds: 10
#         periodSeconds: 3
#         successThreshold: 1
#         timeoutSeconds: 1
#       resources: {}
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       volumeMounts:
#         - mountPath: /etc/clickhouse-server/config.d/
#           name: chi-simple-01-common-configd
#         - mountPath: /etc/clickhouse-server/users.d/
#           name: chi-simple-01-common-usersd
#         - mountPath: /etc/clickhouse-server/conf.d/
#           name: chi-simple-01-deploy-confd-simple-0-0
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-4npmh
#           readOnly: true