apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: cluster-01
spec:
  defaults:
    templates:
      podTemplate: pod-template-with-volumes
      dataVolumeClaimTemplate: data-volume-template

  configuration:
    clusters:
      - name: "cluster-01"
        layout:
          shardsCount: 1
          replicasCount: 1

  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              livenessProbe:
                exec:
                  command:
                  - sh
                  - -c
                  - wget -qO- localhost:8123/ping
              readinessProbe:
                exec:
                  command:
                  - sh
                  - -c
                  - wget -qO- localhost:8123/ping

    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          # storageClassName: gp2-resizable
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

