apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse-01
spec:
  defaults:
    templates:
      serviceTemplate: cluster-service
      podTemplate: pod-template-with-health-check
      dataVolumeClaimTemplate: data-volume-template

  configuration:
    clusters:
      - name: clickhouse-01
        layout:
          shardsCount: 1
          replicasCount: 1

  templates:
    serviceTemplates:
      - name: cluster-service
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 80
              targetPort: 8123
            - name: tcp
              port: 9000
              targetPort: 9000

    podTemplates:
      - name: pod-template-with-health-check
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              livenessProbe:
                failureThreshold: 10
                exec:
                  command:
                  - sh
                  - -c
                  - wget -qO- localhost:8123/ping
                initialDelaySeconds: 60
                periodSeconds: 3
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                exec:
                  command:
                  - sh
                  - -c
                  - wget -qO- localhost:8123/ping
                initialDelaySeconds: 10
                periodSeconds: 3
                successThreshold: 1
                timeoutSeconds: 1
            # resources:
            #   requests:
            #     memory: "512Mi"
            #     cpu: "500m"
            #   limits:
            #     memory: "512Mi"
            #     cpu: "500m"

    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          # storageClassName: gp2-resizable
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse
  namespace: clickhouse

spec:
  ingressClassName: nginx

  rules:
    - host: clickhouse.local.com.br
      http:
        paths:
          - path: "/*"
            pathType: Prefix
            backend:
              service:
                name: clickhouse-clickhouse-01
                port:
                  number: 80
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: clickhouse
#   namespace: clickhouse
# spec:
#   ports:
#     - name: http
#       port: 80
#       protocol: TCP
#       targetPort: http
#   selector:
#     clickhouse.altinity.com/cluster: clickhouse-01
