apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: clickhouse-01
  namespace: clickhouse
spec:
  defaults:
    templates:
      clusterServiceTemplate: cluster-service-template
      podTemplate: pod-with-health-check-template
      dataVolumeClaimTemplate: data-volume-template

  configuration:
    clusters:
      - name: clickhouse-01
        layout:
          shardsCount: 1
          replicasCount: 1

  templates:
    serviceTemplates:
      - name: cluster-service-template
        generateName: "clickhouse-{chi}"
        spec:
          type: ClusterIP
          ports:
            - name: http
              port: 8123
            - name: client
              port: 9000
            - name: interserver
              port: 9009

    podTemplates:
      - name: pod-with-health-check-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
              livenessProbe:
                failureThreshold: 10
                exec:
                  command:
                  - sh
                  - -c
                  - wget -qO- localhost:8123/ping
                initialDelaySeconds: 60
                periodSeconds: 3
                successThreshold: 1
                timeoutSeconds: 1
              readinessProbe:
                failureThreshold: 3
                exec:
                  command:
                  - sh
                  - -c
                  - wget -qO- localhost:8123/ping
                initialDelaySeconds: 10
                periodSeconds: 3
                successThreshold: 1
                timeoutSeconds: 1
            # resources:
            #   requests:
            #     memory: "512Mi"
            #     cpu: "500m"
            #   limits:
            #     memory: "512Mi"
            #     cpu: "500m"

    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          # storageClassName: gp2-resizable
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse-ingress
  namespace: clickhouse
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - host: clickhouse.local.com.br
          path: /
          pathType: Prefix
          backend:
            service:
              name: clickhouse-clickhouse-01
              port:
                number: 8123     