apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse

resources:
 - https://github.com/Altinity/clickhouse-operator/raw/0.21.3/deploy/operator/clickhouse-operator-install-bundle.yaml