apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry
  namespace: debezium
data:
  # https://docs.confluent.io/platform/7.0/schema-registry/installation/config.html

  SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-controller-0.kafka-controller-headless.kafka:9092

  SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
  # SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_TYPE: "PEM"
  # SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTORE_TYPE: "PEM"

  SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: schema-registry-local
  SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas_local
  SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS: "2000"

  # SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: SCRAM-SHA-256
  # SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_SSL
  # SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="password";

  SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
  SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
  SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="password";