apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-kafka
  namespace: debezium
  labels:
    application: schema-registry-kafka
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      application: schema-registry-kafka
  template:
    metadata:
      labels:
        application: schema-registry-kafka

    spec:
      volumes:
        - name: kafka-certs
          projected:
            defaultMode: 256
            sources:
              - secret:
                  name: kafka-tls-secret

      containers:
        - name: schema-registry-kafka
          image: confluentinc/cp-schema-registry:7.0.1
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_TYPE
              value: "PEM"
            - name: SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_CERTIFICATES
              value: "-----BEGIN CERTIFICATE-----\nMIIDETCCAfmgAwIBAgIQOXb8m/PvLkb6DCF8AV6Z6jANBgkqhkiG9w0BAQsFADAT\nMREwDwYDVQQDEwhrYWZrYS1jYTAeFw0yMzA4MjMxMDE2MjBaFw0yNDA4MjIxMDE2\nMjBaMBMxETAPBgNVBAMTCGthZmthLWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\nMIIBCgKCAQEA0tjTdijfGdpNU0K4BTgblhljAU3ukXY2QzeY519oRpUevXMmqsYx\nJUMBMm21mc6kIYnSlzKGlEe46Z+se07j2xNCK/iMwuzrxT3N3We0AF0IsEJxki+Q\nEOSspXEuwh/7HzAJOP3FKNxlrLrJOgpr0YpM4n6vb4oQF+Y1wrTvg635g9qIm8Vr\nrkuFd11+GLQZANzZ7HDxpbaF2jW2oYeE5t5cYa5eBmSDf71RhXERzzNHAHaREu0F\nwrTyFs0mDoryacaKbDokWuel2D122+s0K7shhj/eqJimdt7FeG7gO1CGHR0ioVY7\na8gusVGSr53VGCLMKt5uuB4ZTtPCSws1nwIDAQABo2EwXzAOBgNVHQ8BAf8EBAMC\nAqQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMB\nAf8wHQYDVR0OBBYEFGAV4qXp0PLD2i6qNeh9shjvFFSnMA0GCSqGSIb3DQEBCwUA\nA4IBAQAAj0CAQFOrlfOKMODOR21dO6gS+RqCDRJGTJzfGTk4yIrwCRACHXqJbMJo\nk/TMIk5MOArZgv7e7kv4YZLQPeXQLorrciCOkPg0Rmyl1s0GdHWAu7ZFvnKKrri8\n/ZHBLkTDKOV1GdzezwOUxdGmY9hE7nEItzUQYkYJ8aEK9z3zVdyE92I4W0RvYHBf\nHiBdX383S/dLbgPQE5bFOLNXgC3iYNs4GJH5CPDWlE2Ghkven37Y5ItgAE/ARN6U\nH86Wfr1qhT1Kc+H0anpu81s/GsjXDJd40JvEymAPFRvAoL+NxZGlErS2YXKCG1cb\nHYNvtGi/ItovTAS5+46rpzlgk8c1\n-----END CERTIFICATE-----\n"
            # - name: SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_CERTIFICATES
            #   valueFrom:
            #     secretKeyRef:
            #       name: kafka-tls-secret
            #       key: kafka-ca.crt

          envFrom:
            - configMapRef:
                name: schema-registry
   
          ports:
            - containerPort: 8081

          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 240
            successThreshold: 1
            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 6

          # resources:
          #   requests:
          #     memory: "250Mi"
          #     cpu: "200m"
          #   limits:
          #     memory: "250Mi"
          #     cpu: "200m"
