apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-kafka
  namespace: debezium
  labels:
    application: schema-registry-kafka
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      application: schema-registry-kafka
  template:
    metadata:
      labels:
        application: schema-registry-kafka

    spec:
      volumes:
        - name: kafka-certificates
          secret:
            defaultMode: 288
            secretName: kafka-tls-secret

      containers:
        - name: schema-registry-kafka
          image: confluentinc/cp-schema-registry:7.0.1
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION
              value: "/opt/bitnami/kafka-exporter/certs/kafka-ca.crt"
            - name: SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION
              value: "/opt/bitnami/kafka-exporter/certs/kafka.crt"
            - name: SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD
              value: ""
            - name: SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_TYPE
              value: "PEM"
            # - name: SCHEMA_REGISTRY_KAFKASTORE_SSL_TLS_ENABLED
            #   value: "true"


          envFrom:
            - configMapRef:
                name: schema-registry

          volumeMounts:
            - mountPath: /opt/bitnami/kafka-exporter/certs/
              name: kafka-certificates
              readOnly: true

          ports:
            - containerPort: 8081

          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 300
            periodSeconds: 30
            timeoutSeconds: 240
            successThreshold: 1
            failureThreshold: 6

          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 6

          # resources:
          #   requests:
          #     memory: "250Mi"
          #     cpu: "200m"
          #   limits:
          #     memory: "250Mi"
          #     cpu: "200m"
