kind: Service
apiVersion: v1
metadata:
  name: schema-registry-kafka
  namespace: debezium
spec:
  type: ClusterIP
  selector:
    application: schema-registry-kafka
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
