apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium
  namespace: debezium
data:

  REST_HOST_NAME: 0.0.0.0
  BOOTSTRAP_SERVERS: kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local.:9092
  HEAP_OPTS: -XX:MinRAMPercentage=60.0 -XX:MaxRAMPercentage=75.0
  
  KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
  VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter

  GROUP_ID: api-db-local-group
  CONFIG_STORAGE_TOPIC: api-db-local-config # topic to use for storing connector and task configurations
  OFFSET_STORAGE_TOPIC: api-db-local-offsets
  STATUS_STORAGE_TOPIC: api-db-local-status


  # Note: The maximum size of a request in bytes. This setting will limit the number of record batches the producer will send in a single request to avoid sending huge requests. 
  CONNECT_MAX_REQUEST_SIZE: "10485760" # default 1048576

  CONNECT_SASL_MECHANISM: SCRAM-SHA-256
  CONNECT_SECURITY_PROTOCOL: SASL_SSL
  CONNECT_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="password";
  
  CONNECT_PRODUCER_SASL_MECHANISM: SCRAM-SHA-256
  CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_SSL
  CONNECT_PRODUCER_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required username="user" password="password";

  CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081