apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clickhouse

resources:
 - deploy.yaml
 - ingress.yaml
 - service.yaml
 - https://github.com/Altinity/clickhouse-operator/raw/0.21.3/deploy/operator/clickhouse-operator-install-bundle.yaml